add JSONLD schema DSS and Schema DSS_model
H2020-IPM-Decisions/formats pull request #2
Opened 2020-07-06 15:55 UTC by mlabadie

2020-07-29 10:57 UTC, pradal commented
This PR is superseed by #3

2020-07-29 10:59 UTC, pradal commented on DSS_metadata/DSS_model.jsonld
> +        "ipm": "https://raw.githubusercontent.com/H2020-IPM-openalea/formats/master/schema_Terms_from_VIPS.md/",
Use H2020-IPM-Decisions instead

2020-07-29 11:05 UTC, pradal requested changes

2020-07-29 11:05 UTC, pradal commented on schema_Terms_from_VIPS.md
> +Json-ld: <https://json-ld.org/>
Json-ld: <https://json-ld.org>

2020-07-29 11:05 UTC, pradal commented on schema_Terms_from_VIPS.md
> +1. DSS_schema context (VIPS): DSS_schema.jsonld
VIPS need to be an example not in the definition of the schema

2020-09-01 08:05 UTC, treinar commented
As requested by @pradal, this pull request is now closed.

2020-09-01 08:05 UTC, closed without merging